name: Build Xero KDE ISO

on:
  workflow_dispatch:
inputs:
  sf-project: xerolinux-iso-actions
    description: 'sf upload credentials'
    required: true
  sf-user: ${{ secrets.SF_USER_NAME }}
    description: 'sf upload credentials'
    required: true
  sf-key: ${{ secrets.SF_PRIV_SSHKEY }
    description: 'sf upload credentials'
    required: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: write

    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - uses: actions/checkout@v2

      - name: Set current date as environment variable
        run: echo "DATE=`date +'%Y.%m.%d'`" >>$GITHUB_ENV
        
      - name: Create temporary build directory
        run: mkdir -p /tmp/$DATE/airootfs/root/
        
      - name: Update packages and install archiso
        run: pacman -Syu --noconfirm archiso mkinitcpio-archiso git squashfs-tools

      - name: Copy profile to build directory
        run: cp -r ./archiso /tmp/$DATE
        
      - name: Build ISO
        run: bash build.sh
        
      - name: upload-sourceforge
        shell: bash
        env:
          sf-project: xerolinux-iso-actions
          sf-user: ${{ secrets.SF_USER_NAME }}
          sf-key: ${{ secrets.SF_PRIV_SSHKEY }}
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |        
         ssh-keyscan -t rsa frs.sourceforge.net >> /tmp/runner/.ssh/known_hosts
         echo "${{ inputs.sf-key }}" >> /tmp/runner/.ssh/github_actions
         ssh-add /tmp/runner/.ssh/github_actions
         ## upload
         rsync -vaP --stats -e ssh /tmp/$DATE \ ${{ inputs.sf-user }}@frs.sourceforge.net:/home/frs/project/${{ inputs.sf-project }}/kde-iso
