name: Build Xero KDE ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: write

    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - uses: actions/checkout@v2

      - name: Set current date as environment variable
        run: echo "DATE=`date +'%Y.%m.%d'`" >>$GITHUB_ENV
        
      - name: Update packages and install archiso
        run: pacman -Syu --noconfirm archiso mkinitcpio-archiso git squashfs-tools openssh rsync
        
      - name: Build ISO
        run: |
          pacman -S --noconfirm --needed archlinux-keyring wget
          wget https://raw.githubusercontent.com/theCode-Breaker/kde_iso/main/archiso/airootfs/etc/pacman.d/xero-mirrorlist -O /etc/pacman.d/xero-mirrorlist
          mkarchiso -v -w ./work -o ./out ./archiso/
          echo "ISO Built in ./out folder!"
        
      - name: upload-sourceforge
        shell: bash -O extglob {0}
        env:
         SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          echo "## ssh setup"
          mkdir -p /tmp/runner/.ssh
          touch /tmp/runner/.ssh/github_actions
          echo "${{ secrets.SF_PRIV_SSHKEY }}" >> /tmp/runner/.ssh/github_actions
          chmod 600 /tmp/runner/.ssh/github_actions
          ssh-agent -a /tmp/ssh_agent.sock > /dev/null
          ssh-keyscan -t ed25519 frs.sourceforge.net >> /tmp/runner/.ssh/known_hosts
          ssh-add /tmp/runner/.ssh/github_actions
          ## upload
          rsync -avP -e ssh ./out ${{ secrets.SF_USER_NAME }}@frs.sourceforge.net:/home/frs/project/xerolinux-iso-actions/kde-iso
