name: Build Xero KDE ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: write

    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - uses: actions/checkout@v2

      - name: Set current date as environment variable
        run: echo "DATE=`date +'%Y.%m.%d'`" >>$GITHUB_ENV
        
      - name: Create temporary build directory
        run: mkdir -p /tmp/$DATE/airootfs/root/
        
      - name: Update packages and install archiso
        run: pacman -Syu --noconfirm archiso mkinitcpio-archiso git squashfs-tools

      - name: Copy profile to build directory
        run: cp -r ./archiso /tmp/$DATE
        
      - name: Build ISO
        run: bash build.sh
        
      - name: upload-sourceforge
        shell: bash -O extglob {0}
        env:
         SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          echo "## ssh setup"
          mkdir -p /home/runner/.ssh
          touch /home/runner/.ssh/github_actions
          echo "${{ secrets.SF_PRIV_SSHKEY }}" >> /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a /tmp/ssh_agent.sock > /dev/null
          ssh-keyscan -t ed25519 frs.sourceforge.net >> /home/runner/.ssh/known_hosts
          ssh-add /home/runner/.ssh/github_actions
          ## upload
          rsync -avP -e ssh ./out ${{ secrets.SF_USER_NAME }}@frs.sourceforge.net:/home/frs/project/xerolinux-iso-actions/kde-iso
